package view;

import consulta.ListaConsulta;
import consulta.Animais;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import consulta.AnimaisDAO;
import view.TelaPerfil;

import javax.swing.table.DefaultTableModel;


public final class TelaInicial extends javax.swing.JFrame {
    CadastroConsulta cadastro = new CadastroConsulta();
    DetalheConsulta finalizaConsul = new DetalheConsulta();
    
    
    
    
    private int idAdotante;
    /**
     * Creates new form TelaInicial
     */
    public TelaInicial(int idAdotante) {
        initComponents();
        executaMetodo();
        this.idAdotante = idAdotante;
    }
    
    
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnCadastroConsulta = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnFinalizar = new javax.swing.JButton();
        JScrollPane = new javax.swing.JScrollPane();
        tblPets = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        btnPerfil = new javax.swing.JButton();

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gab\\Downloads\\ChatGPT Image 29 de jan. de 2026, 14_40_13 (1).png")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Boas vindas a lista de pets disponíveis para adoção!");

        btnCadastroConsulta.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnCadastroConsulta.setText("Cadastrar Pet");
        btnCadastroConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroConsultaActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnExcluir.setText("Excluir Pet");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnFinalizar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnFinalizar.setText("Adotar Pet");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        tblPets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Raça", "Abrigo", "Adotado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        JScrollPane.setViewportView(tblPets);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gab\\Downloads\\ChatGPT Image 29 de jan. de 2026, 14_40_13 (1).png")); // NOI18N

        btnPerfil.setText("PERFIL");
        btnPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btnCadastroConsulta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExcluir)
                .addGap(212, 212, 212)
                .addComponent(btnFinalizar)
                .addGap(28, 28, 28))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(JScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 787, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(96, 96, 96)
                        .addComponent(btnPerfil)
                        .addGap(37, 37, 37))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(btnPerfil))
                        .addGap(18, 18, 18)
                        .addComponent(JScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastroConsulta)
                    .addComponent(btnExcluir)
                    .addComponent(btnFinalizar))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastroConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroConsultaActionPerformed
        cadastro.MostraTela(this);
    }//GEN-LAST:event_btnCadastroConsultaActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        finalizaConsul.MostraTela(this);
        finalizaConsul.setIdAdotante(idAdotante); 
    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        excluirConsulta(pegaPosicao());
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilActionPerformed
     TelaPerfil perfil = new TelaPerfil(idAdotante);
    perfil.setVisible(true); 
        
    }//GEN-LAST:event_btnPerfilActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JScrollPane;
    private javax.swing.JButton btnCadastroConsulta;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTable tblPets;
    // End of variables declaration//GEN-END:variables
    
    
    
    private final String[] colunas = {"Nome", "Raça", "Abrigo", "Adotado", "Adotante"};
    
    DefaultTableModel tabelaModelo = new DefaultTableModel(colunas, 0);
    
    
    
   private void atualizar() {

    AnimaisDAO dao = new AnimaisDAO();
    List<Animais> listaConsulta = dao.listar();

    DefaultTableModel tabelaModelo = new DefaultTableModel(colunas, 0);

    for (Animais a : listaConsulta) {

        String adotante;

        if (a.getAdotante_id() == 0) {
            adotante = "Nenhum";
        } else {
            adotante = "ID " + a.getAdotante_id();
        }

        String[] linha = {
            a.getNome(),
            a.getRaca(),
            a.getAbrigo(),
            a.getAdotado(),
            adotante
        };

        tabelaModelo.addRow(linha);
    }

    tblPets.setModel(tabelaModelo);
}

    
    public void executaMetodo(){
        atualizar();
    
    }
    
    public int pegaPosicao(){
        
        int posicao = tblPets.getSelectedRow();
        
        if(posicao == -1){
            JOptionPane.showMessageDialog(rootPane, "Selecione um pet!");
        
        }
        
        return posicao;
    }
    
 public void excluirConsulta(int posicao) {

    if (posicao >= 0) {

        int opcao = JOptionPane.showConfirmDialog(
            rootPane,
            "Deseja excluir este pet?",
            "Excluir",
            JOptionPane.YES_NO_OPTION
        );

        if (opcao == JOptionPane.YES_OPTION) {

            Animais a = seleciona(posicao);
            AnimaisDAO dao = new AnimaisDAO();
            dao.excluir(a.getId());
            atualizar();
        }
    }
}


    
    public Animais seleciona(int pose) {
    AnimaisDAO dao = new AnimaisDAO();
    return dao.listar().get(pose);
}

}
